version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - '3000:3000'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: agri_farm
      POSTGRES_PASSWORD: Chibao2002_
      POSTGRES_DB: agri_farm
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: agri_farm
      POSTGRES_PASSWORD: Chibao2002_
      POSTGRES_DB: agri_farm
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
