version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploadFile:/app/dist/uploadFile  # Maps host `uploadFile` folder to container
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
    restart: always

volumes:
  uploadFile:
