version: '3'
services:
  app:
    image: baohc1109/agri-farm-server:lastest
    container_name: agri-farm-server:lastest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
