version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploadFile:/app/dist/uploadFile  # Maps host `uploadFile` folder to container
    environment:
      - NODE_ENV=production
    restart: always

volumes:
  uploadFile:
