export enum NotificationTitleEnum {
  create_report_land = 'Yêu cầu tạo báo cáo đất',
  new_booking = 'Yêu cầu thuê đất mới được tạo',
  booking_pending_sign = 'Yêu cầu thuê đất đang chờ ký tên',
  booking_rejected = 'Yêu cầu thuê đất của bạn đã bị từ chối',
  booking_completed = 'Thanh toán thành công cho yêu cầu thuê đất',
  booking_pending_payment = 'Thanh toán cho yêu cầu thuê đất đang chờ xử lý',
  create_task = 'Bạn có một nhiệm vụ mới',
  report_purchase = 'Báo cáo kết quả kiểm định trước thu hoạch',
  report_harvest = 'Báo cáo kết quả thu hoạch',
  request_extend = 'Yêu cầu gia hạn thuê đất',
  pending_sign_extend = 'Yêu cầu gia hạn thuê đất đang chờ ký tên',
  reject_request_purchase = ' Chất lượng sản phẩm không đạt yêu càu',
  ready_process_stage = `Chuẩn bị cho giai đoạn mới`,
  manager_booking_pending_sign = 'Hợp đồng thuê đất mới được tạo',
  staff_booking_pending_sign = 'Hợp đồng thuê đất đang chờ ký tên',
  create_chat = 'Cuộc trò chuyện mới đã được tạo',
  create_report = 'Báo cáo cho công việc mới được tạo',
  booking_refund = 'Yêu cầu hoàn tiền đã được tạo',
  create_extend = 'Yêu cầu gia hạn thuê đất vừa được tạo',
  pending_payment_extend = 'Yêu cầu gia hạn thuê đất đang chờ thanh toán',
  extend_completed = 'Thanh toán gia hạn thuê đất thành công',
  reject_extend = 'Yêu cầu gia hạn thuê đất của bạn đã bị từ chối',
  update_material_specific_stage = 'Cập nhật vật liệu cho giai đoạn cụ thể',
  warning_material_specific_stage = 'Cảnh báo vật liệu cho giai đoạn cụ thể không đủ',
}
