name: Build and Deploy Docker Agri-farm-server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      -users: actions/checkouts@v3

      -name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -name: create .env file
        run: echo "${{ secrets.ENV }}" || base64 -d > .env

      -name: Build Docker Image
        run: docker build -t agri-farm-server .

      -name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/agri-farm-server

      -name: Upload image metadata
        uses: actions/metadata-action@v2
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/agri-farm-server:latest
          tags: 
            ${{ github.sha }}
