# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Node.js
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       # Install dependencies
#       - name: Install dependencies
#         run: npm install

#       # Run unit tests
#       - name: Run tests
#         run: npm run test

#       # Build the project
#       - name: Build the project
#         run: npm run build

#       # Login to Server
#       - name: Login to Server
#         run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} -i ${{ secrets.SERVER_SSH_KEY }}

#       # Set up Docker
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_PASSWORD }}

#       # Build and push Docker image to Docker Hub
#       - name: Build and push Docker image
#         run: |
#           docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/agri-farm-server:latest .
#           docker push ${{ secrets.DOCKER_HUB_USERNAME }}/agri-farm-server:latest

#       # Deploy to server via SSH
#       - name: Deploy to server
#         uses: appleboy/ssh-action@v0.1.8
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           password: ${{ secrets.SERVER_PASSWORD }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/agri-farm-server:latest || true
#             docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/agri-farm-server:latest
#             docker stop agri-farm-server || true
#             docker rm agri-farm-server || true
#             docker run -d --name agri-farm-server -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/agri-farm-server:latest
